server:
  port: 8888

# 구성 서버에서 Vault 백엔드 활성화하기
spring:
  profiles:
    active:
      - vault
      - git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yunyoung1819/tacocloud-config
          order: 2
        vault:
          host: localhost
          port: 8200
          scheme: http
          order: 1